version: "3"

services:
  app:
    build: "./app"
    command: "uvicorn main:app --reload"
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/work/app
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:14
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/db
    ports:
      - "5432:5432"

volumes:
  pgdata:
